CineBundle\Entity\Cine:
    type: entity
    table: cine
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        ubicacion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        cantSalas:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: cant_salas
        estado:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
