retiraentrada:
    resource: "@RetiraentradaBundle/Resources/config/routing.yml"
    prefix:   /

cine:
    resource: "@CineBundle/Resources/config/routing.yml"
    prefix:   /
app:
    resource: "@AppBundle/Controller/"
    type:     annotation