RetiraentradaBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        dni:
            type: integer
            nullable: true
            options:
                unsigned: false
        estado:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        mail:
            type: string
            nullable: true
            length: 140
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 140
            options:
                fixed: false
        role:
            type: string
            nullable: true
            length: 140
            options:
                fixed: false
        fechaNac:
            type: string
            nullable: true
            length: 11
            options:
                fixed: false
            column: fecha_nac
        apellido:
            type: string
            nullable: true
            length: 140
            options:
                fixed: false
    lifecycleCallbacks: {  }
